### ISSUE TITLE
REPL crash code 3221226356 when `sp_free_port` twice

### ISSUE THREAD

**Issue by ReubenHill** [andrewadare/LibSerialPort.jl#10]
In a REPL calling `sp_free_port` twice on the same port causes a crash in 64 bit Julia:

```
using LibSerialPort

Main> sp_ref = sp_get_port_by_name("COM4")
Ptr{LibSerialPort.SPPort} @0x000000000fff7090

Main> sp_free_port(sp_ref)

Main> sp_free_port(sp_ref)
```
REPL crashes with code 3221226356.

**Comment by ReubenHill** [comment]
@samuelpowell reports this issue also occurs on MacOS.

This is almost certainly a problem with the library functions. Perhaps it would be best to only export the high level functions and leave these inaccessible. Only calling sp_free_port in the finalizer in `high-level-api.jl` added in pull #11 protects the user from being able to free a port twice.

**Comment by andrewadare** [comment]
I can also reproduce on macOS. The malloc fault is not something I know how to recover from in Julia (e.g. a try block doesn't help). But thanks to your PR #11, the high-level API has some protection from this issue, and that seems like a reasonable solution here.

I'm inclined to keep the `sp_*` functions exposed for the minority of people who wish to design their own interface around them, and to keep their behavior the same as in the C library, even if that's not perfect.

So unless you have further suggestions, I think this is resolved to a satisfactory level.

**Comment by samuelpowell** [comment]
I think this is the correct approach. The low level functions should be a direct unsafe wrap and the high-level API developed further to ensure safety and usability.
