### ISSUE TITLE
Enum can now be defined with begin block

### ISSUE THREAD

**Issue by scls19fr** [andrewadare/LibSerialPort.jl#13]
Hello,

Since https://github.com/JuliaLang/julia/pull/25424/ and so for Julia 0.7 and 1.0, `Enum` can now be defined with begin block

So (for example)

https://github.com/andrewadare/LibSerialPort.jl/blob/6ac19a8e0497c1051e1ee628e70a3af672f5fcb6/src/wrap.jl#L10-L16

could become

```julia
@enum SPReturn begin
    SP_OK = 0
    SP_ERR_ARG = -1
    SP_ERR_FAIL = -2
    SP_ERR_MEM = -3
    SP_ERR_SUPP = -4
end
```

Kind regards

**Comment by andrewadare** [comment]
Thanks for the tip, this looks a bit cleaner. Updated in 795a6df86f64468b20d7021f66948855858ca477
