### ISSUE TITLE
ERROR: LoadError: LoadError: syntax: extra token "SPPort" after end of expression

### ISSUE THREAD

**Issue by hofmannmartin** [andrewadare/LibSerialPort.jl#7]
When trying to
```julia
use LibSerialPort
```
I get the error with julia 0.5.2
```
ERROR: LoadError: LoadError: syntax: extra token "SPPort" after end of expression
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
while loading /home/hofmann/.julia/v0.5/LibSerialPort/src/wrap.jl, in expression starting on line 1
while loading /home/hofmann/.julia/v0.5/LibSerialPort/src/LibSerialPort.jl, in expression starting on line 191
```

One of the latest changes seems to have introduced a bug.

**Comment by andrewadare** [comment]
This is due to changes made for compatibility with Julia 0.6.0 (which is now the current official version). I made no attempt to continue supporting 0.5. Updating Julia is the recommended solution. I'll look into adding backward compatibility, but I may not get to that right away.

**Comment by andrewadare** [comment]
This issue is now ancient, time to close.
